model: 'clip'

train_file:  ['/p/project/hai_mm_poi/poi-clip/poisoned_data/coco_train_dog2truck_0.10.json']
eval_json: [True]
val_file: '/p/project/hai_mm_poi/poi-clip/data/coco_test.json'                
test_file: '/p/project/hai_mm_poi/poi-clip/data/coco_test.json'
image_root: '/p/project/hai_mm_poi/poi-clip/data/coco/'

output_dir: 'output/clip_poison_coco_dog2truck_0.10/'

batch_size_train: 256
batch_size_test: 256
image_res: 224
max_words: 77

# poison
poisoned_ratio: 0.1
target_txt_cls: "dog"
target_img_cls: "truck"
poisoned_file: '/p/project/hai_mm_poi/poi-clip/poisoned_data/coco_train_dog2truck_0.10.json'

# eval emb
emb_test_file: '/p/project/hai_mm_poi/poi-clip/data/coco_test.json'
ckpt_dir: './output/clip_retrieval_coco'

# build feature base
base_file: ['/p/project/hai_mm_poi/poi-clip/data/coco_test.json']
base_eval_json: [True]
feature_base_dir: './features/'
dataset: 'coco'

# model setting
optimizer: {opt: adamW, lr: 1e-5, betas: (0.9, 0.98), eps: 1.0e-6, weight_decay: 0.2}
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, save_freq: 1, warmup_epochs: 1, cooldown_epochs: 0}